name: Generate Pacman Contribution Graph

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate Pacman
        uses: Platane/snk@v3
        with:
          github_user_name: Joao-Victorx
          outputs: |
            dist/pacman.svg?palette=github-dark&animation=pacman

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
