name: Generate Pacman

on:
  schedule:
    - cron: "0 0 * * *" # Roda todo dia à meia-noite
  workflow_dispatch: # Permite rodar manualmente
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Generate Pacman Animation
        uses: lowlighter/metrics@latest
        with:
          filename: github-contribution-grid-pacman.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
